import '@/styles/globals.css'

import type { Metadata } from 'next'
import { roboto } from '../styles/fonts'

export const metadata: Metadata = {
  title: 'next-stroybook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
